services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: unless-stopped
    network_mode: host  # Host mode for proper WebRTC/RTSP UDP handling
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro

  hydro-app:
    build: .
    container_name: hydro-production
    network_mode: host  # Use host network to access mosquitto on localhost
    volumes:
      - ./hydro.db:/app/hydro.db  # Persist database
      - hydro-data:/app/data      # Additional data persistence
    environment:
      - NODE_ENV=production
      - PORT=3001
      - API_PORT=8001
      - MQTT_BROKER=127.0.0.1
    restart: unless-stopped
    depends_on:
      - mediamtx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  hydro-data:
    driver: local
